### ISSUE TITLE
Aplicación con realidad aumentada

### ISSUE THREAD

**Issue by valeria1418** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-valeria1418#2]
Analizar dos aplicaciones, una con realidad aumentada y otra con realidad virtual

**Comment by valeria1418** [comment]
[practica 1.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-valeria1418/files/6105791/practica.1.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien realizdo y revisado
